default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
cache: &cache
  <<: *default
  migrations_paths: db/cache_migrate
queue: &queue
  <<: *default
  migrations_paths: db/queue_migrate

development:
  primary:
    <<: *default
    database: waxc_development
  cache:
    <<: *cache
    database: waxc_development_cache
  queue:
    <<: *queue
    database: waxc_queue
  cable:
    <<: *default
    database: waxc_development_cable
    migrations_paths: db/cable_migrate
test:
  <<: *default
  database: waxchromatics_mono_test
production:
  primary: &primary_production
    <<: *default
    database: waxchromatics_mono_production
    username: waxchromatics_mono
    password: <%= ENV["WAXCHROMATICS_MONO_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: waxchromatics_mono_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: waxchromatics_mono_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: waxchromatics_mono_production_cable
    migrations_paths: db/cable_migrate
